alias rchainclean='sbt clean rholang/bnfc:clean rholang/bnfc:generate'
alias rchaincompile='_JAVA_OPTIONS="-Xms2G -Xmx4G -Xss2m -XX:MaxMetaspaceSize=1G -Dsbt.task.timings=true -Dsbt.task.timings.on.shutdown=true -Dsbt.task.timings.threshold=2000" sbt compile'
alias rchaindocker='sbt node/docker:publishLocal'
alias rchainrecompile='_JAVA_OPTIONS="-Xms2G -Xmx4G -Xss2m -XX:MaxMetaspaceSize=1G -Dsbt.task.timings=true -Dsbt.task.timings.on.shutdown=true -Dsbt.task.timings.threshold=2000" sbt clean rholang/bnfc:clean rholang/bnfc:generate compile node/docker:publishLocal'
alias buildrchaintestimage='docker build -t rchain-integration-tests:latest .'
